services:
  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: wonderadmin
      POSTGRES_PASSWORD: wonderpass
      POSTGRES_DB: wonderkidsdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: wonder-backend
    restart: always
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgres://wonderadmin:wonderpass@db:5432/wonderkidsdb
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - /app/node_modules #évite les conflits entre host et conteneur

  frontend:
    build: ./frontend
    container_name: wonder-frontend
    restart: unless-stopped
    ports:
      - "5173:80"


volumes:
  postgres-data: